djcrm/urls.py
from django.contrib import admin
from django.urls import path,include
from leads.views import LadingPage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("leads.urls", namespace="leads")),
    

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

#CRUD+L : CREATE RETRIERVE UPDATE AND DELETE VIEWS+LIST

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"

urlpatterns =[
    path('landing',views.landing, name="landing"),
    path('', views.LeadListView.as_view(),name="index"),
    path('<int:pk>', views.lead_details, name="details"),
    #path("details", views.lead_details, det),
    path("create/", views.lead_create, name="create"),
    path('update/<int:pk>', views.update, name = "update"),
    path('delete/<int:pk>', views.delete, name="delete")
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

# Create your models here.
class Lead(models.Model):
    SOURCE_CHOICES  = (
        ('Youtube','Youtube'),
        ('Google','Google')
    )
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    age = models.IntegerField(default=0)

    agent = models.ForeignKey("Agent", on_delete=models.CASCADE)

    '''phoned = models.BooleanField(default=False)
    source = models.CharField(choices=SOURCE_CHOICES, max_length=100)
    profile_picture = models.ImageField(blank=True, null=True)
    file = models.FileField(blank=True, null=True)'''

    def __str__(self):
        return f"{self.first_name}- {self.last_name}"

    #FOREIGN KEY ISSUES

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

leads/forms.py
from django import forms
from .models import Lead

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent'
        )
class LeadForm(forms.Form):
    first_name = forms.CharField(max_length=120)
    last_name = forms.CharField(max_length=120)
    age = forms.IntegerField()

leads/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
# Create your views here.
from .models import Lead,Agent
from .forms import LeadForm,LeadModelForm

from django.views.generic import TemplateView,ListView

def landing(request):
    return render(request, 'landing.html')

def home_page(request):
    leads = Lead.objects.all()
    context = {
        "leads":leads
    }
    return render(request, 'leads/layout.html', context)

def lead_details(request, pk):
    print(pk)
    lead = Lead.objects.get(id=pk)
    context={
        "lead":lead
    }
    print(lead)
    return render(request, 'leads/details.html',context)

def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        print("received")
        form = LeadModelForm(request.POST)
        if form.is_valid():
            print("form valid")
            print(form.cleaned_data)
            form.save()
            print("lead created")
            return redirect('/')
    context = {
        "form":form
    }
    return render(request, "leads/lead_create.html",context)

def update(request,pk):
    lead= Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        form =LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/")
    context={
        "lead":lead,
        "form":form
    }
    return render(request,'leads/update.html',context)

def delete(request,pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/')


#class based views
class LadingPage(TemplateView):
    template_name = "landing.html"

class LeadListView(ListView):
    template_name = "leads/layout.html"
    queryset = Lead.objects.all()
    context_object_name = "leads"

leads/templates/leads/details.html
{% extends "base.html" %}
{%block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
           <a href="{%url 'leads:details' lead.pk %}"class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
          overview</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
          Reviews</a>
          <a href="{%url 'leads:update' lead.pk%}""flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"">
          update Details</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">dummy location</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">cell phone</span>
          <span class="ml-auto text-gray-900">+58778885</span>
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900">$58.00</span>
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>


    <h1>These are the details {{lead.first_name}}</h1>
    <ul>
      
        <div class="lead">
            <a href="{{lead.id}}">{{lead.first_name}}--{{lead.last_name}}--{{lead.age}}</a>
        </div>
        <a href="{%url 'leads:update' lead.pk%}">update</a>
        <a href="{%url 'leads:delete' lead.pk%}">Delete</a>
    </ul>
{%endblock %}

leads/templates/leads/layout.html
{%extends 'base.html'%}

{%block content%}
   <section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <a href="{%url 'leads:create' %}">Create lead</a>
    <hr>
    <div class="flex flex-wrap -m-4">
        {%for lead in leads%}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                {{lead.first_name}} {{lead.last_name}}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{{lead.id}}" class="mt-3 text-indigo-500 inline-flex items-center">view this lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
     {%endfor%}
    </div>
  </div>
</section>


  
{%endblock%}

leads/templates/leads/lead_create.html
{%extends 'base.html'%}
{%block content%}
   <h1>Fill the form</h1>
   <form method="post">
     {%csrf_token%}
     {{form.as_p}}
     <button type="submit">submit</button>
   </form>
{%endblock%}

leads/templates/leads/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Dj crm</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a href={%url 'leads:index'%} class="mr-5 hover:text-gray-900">Leads</a>
      <a class="mr-5 hover:text-gray-900">SignUp</a>
      
    </nav>
    <a class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
    login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
  </div>
</header>

leads/templates/leads/update.html
{% extends "base.html" %}
{%block content%}


<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{%url 'leads:details' lead.pk %}"class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
          overview</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
          Reviews</a>
          <a href="{%url 'leads:update' lead.pk%}"class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
          update Details</a>
        </div>
            <form method="post">
          {%csrf_token%}
          {{form.as_p}}
          <button type="submit">update</button>
        </form>
      
         <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</button>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>


{%endblock%}

templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{%static 'css/styles.css'%}" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="max-w-7xl mx-auto bg-green-100">
    {%include 'leads/navbar.html'%}    
    {%block content%}
    {%endblock%}

    </div>
  <script src="{%static 'JS/main.js'%}">

  </script>
</body>
</html>

templates/landing.html
{%extends 'base.html'%}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Before they sold out
        <br class="hidden lg:inline-block">CRM build with Django
      </h1>
      <p class="mb-8 leading-relaxed">It helps you manage the leeds</p>
      <div class="flex justify-center">
        <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
        <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
    </div>
  </div>
</section>

{% endblock  %}